### ISSUE TITLE
Erreur d'encodage

### ISSUE THREAD

**Issue by francispoisson** [dvd-dev/python-hilo#1]
J'ai toujours cet erreur.

pyhilo.exceptions.RequestError: 404, message='Resource Not Found', url=URL('https://apim.hiloenergie.com/Automation/v1/api%5CLocations%5C1364%5CDevices')

**Comment by francispoisson** [comment]
J'ai fait:
- pip install python-hilo
- j'ai mis le fichier test.py sur mon desktop que j'ai modifé en mettant mon username/password

Version python 3.9.7

**Comment by francispoisson** [comment]
En faisant la modification de la ligne 378 ça fonctionne très bien.

**Comment by francispoisson** [comment]
En fait, j'ai le problème localement, mais pas sur HA. La modification que j'ai fait dans le main règle le problème et n'en ajoute pas.

**Comment by valleedelisle** [comment]
Effectivement, c'est comme s'il y avait un double encodage. Pas sur de comprendre de ou ça vient mais si la patch rêgle ton problème et qu'elle n'en cause pas, on va juste la merger.

**Comment by valleedelisle** [comment]
@francispoisson si tu veux tester l’intégration dans un environnent de test: https://github.com/dvd-dev/hilo/
