### ISSUE TITLE
Defi Hilo passe à "unknown" après la phase recovery

### ISSUE THREAD

**Issue by RayLation** [dvd-dev/python-hilo#162]
sensor.defi_hilo est passé de "reduction" à "unknown" à 11h ici durant un défi. Je ne semble pas le seul selon discussion sur Discord. Ceci est arrivé après la phase recovery, mais avant que le défi soit officiellement terminé et que le sensor tombe à off.

Selon moi, c'est un bug à la ligne 114 dans event.py. Je pense que ca devrait être >= et non <=

![image](https://github.com/dvd-dev/python-hilo/assets/92007174/c368c6a1-d48f-4d32-90ae-4ebb332c02b8)

![image](https://github.com/dvd-dev/python-hilo/assets/92007174/843fee70-c108-4f80-a486-4592f5684793)

**Comment by ic-dev21** [comment]
Question niaiseuse, pourquoi pas off carrément? @valleedelisle vois-tu un cas de figure que je vois pas?

**Comment by RayLation** [comment]
Bien d'accord avec toi. Dailleurs, a ma connaissance, c'était off avant et c'était parfait (pour mes besoins du moins 😀)

**Comment by valleedelisle** [comment]
> Question niaiseuse, pourquoi pas off carrément? @valleedelisle vois-tu un cas de figure que je vois pas?

Normalement, je crois que ça devrait revenir off tout seul, à moins que le caching ait changé ce behavior aussi. J'imagine que completed ça peut être bon pour lancer des automation tout de suite après un défi. Mais si vous pensez que c'est broken et/ou useless, j'ai aucun problème à changer ça pour off.
