### ISSUE TITLE
Serait-ce possible de changer la license du projet?

### ISSUE THREAD

**Issue by Moustachauve** [dvd-dev/python-hilo#47]
J'aimerais contribuer, entre autre en ajoutant le support des lumières RGB. Malheureusement, du à la license du project actuelle (Unlicense license), je n'ai pas le droit de contribuer au projet.

Serait-ce possible de considérer une autre license comme Appache2, MIT ou  GPL-3.0?

Merci!

**Comment by valleedelisle** [comment]
Je crois que MIT est la moins restrictive dans les choix que tu m'as donné. Merci à l'avance pour ta contribution.
